name: 'native_extra_flutter'
description: 'native_extra_flutter is program for help you, booster up your projects significants with amazing features and super easy for use'
version: '0.0.0'
homepage: "https://youtube.com/@azkadev"
repository: "https://github.com/azkadev/native_extra_flutter"
issue_tracker: "https://github.com/azkadev/native_extra_flutter/issues"
documentation: "https://github.com/azkadev/native_extra_flutter"
funding:
  - "https://github.com/sponsors/azkadev"
  - "https://www.patreon.com/c/azkadev"
  - "https://opencollective.com/azkadev"
  - "https://paypal.me/azkaaxeliongibran"
  - "https://paypal.me/azkadev"
environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: 'flutter'
dev_dependencies: 
  flutter_lints: '^5.0.0'
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null


false_secrets:
  - 'android/jniLibs'
  - 'linux/'
  - 'windows/'
  - 'macos/'
  - 'ios/'